### ISSUE TITLE
ROADMAP to 0.1

### ISSUE THREAD

**Issue by rafaelcn** [NewayPix/cell-life#1]
**Game overall**
- [ ] Title state.
- [ ] Game state.
- [ ] Dead state.

**In game**
- [ ] Window camera follows cell trough the map.
- [ ] Random food spawn.
- [ ] The cell grows whenever it eats something, until some specified point, and from that, it evolves to the next _something_.
- [ ] Other cells with self conscience - AI -, though I don't know the behavior that I want them to behave.

**Comment by ryukinix** [comment]
Where is the source of this game anyway?

**Comment by ryukinix** [comment]
Oh, is in the dev branch. I missed that.
